name: compose
services:
    fallout-tradingview:
        cpu_shares: 90
        command: []
        container_name: fallout-dashboard
        deploy:
            resources:
                limits:
                    memory: "16135487488"
        hostname: fallout-dashboard
        image: fallout-tradingview:latest
        networks:
            default: null
        ports:
            - mode: ingress
              target: 80
              published: "8989"
              protocol: tcp
        restart: unless-stopped
networks:
    default:
        name: compose_default
x-casaos:
    author: self
    category: self
    hostname: ""
    icon: ""
    index: /
    is_uncontrolled: false
    port_map: "8989"
    scheme: http
    title:
        custom: Trading View
